In [21]:
import pandas as pd
import warnings
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\User\Downloads\Salary_dataset.csv")

In [39]:
df.head()

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [4]:
df.drop('Unnamed: 0',axis=1 ,inplace=True)

In [5]:
df.head()

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes


In [7]:
df.shape

(30, 2)

In [8]:
X = df[['YearsExperience']]
y = df[['Salary']]

In [25]:
X_train , x_test , y_train , y_test = train_test_split(X,y,test_size = 0.3 , random_state = 1)

In [26]:
X_train

YearsExperience
22              8.0
23              8.3
4               2.3
2               1.6
25              9.1
6               3.1
18              6.0
13              4.2
7               3.3
27              9.7
1               1.4
16              5.2
0               1.2
15              5.0
29             10.6
28             10.4
9               3.8
8               3.3
12              4.1
11              4.1
5               3.0

In [28]:
x_test

YearsExperience
17              5.4
21              7.2
10              4.0
19              6.1
14              4.6
20              6.9
26              9.6
3               2.1
24              8.8

In [29]:
reg = LinearRegression()

In [31]:
reg.fit(X_train, y_train)

LinearRegression()

In [35]:
reg.predict([[2]])

array([[43534.82155213]])

In [36]:
reg.predict([[5.5]])

array([[75742.63914602]])

### ---2nd

#### Importing liabraries

In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")

In [49]:
df = pd.read_csv(r"C:\Users\User\Downloads\Salary_dataset.csv")
df.head()
df.drop('Unnamed: 0' , axis = 1 , inplace = True)
df.head()
X = df[['YearsExperience']]
y = df[['Salary']]
X_train , X_test , y_train , y_test = train_test_split(X , y, test_size = 0.2 , random_state = 1)
reg = LinearRegression()
reg.fit(X_train , y_train)
reg.predict([[2.9]])

array([[51743.14326473]])

In [58]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")
df = pd.read_csv(r"C:\Users\User\Downloads\Salary_dataset.csv")
df.head()
df.drop('Unnamed: 0' , axis= 1 , inplace = True)
df.head()
X = df[['YearsExperience']]
y = df[['Salary']]
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size = 0.3 , random_state = 1)
reg = LinearRegression()
reg.fit(X_train , y_train)
#reg.predict([[Put experiance]])
reg.predict([[5.6]])

array([[76662.86250584]])

In [59]:
X_train

YearsExperience
22              8.0
23              8.3
4               2.3
2               1.6
25              9.1
6               3.1
18              6.0
13              4.2
7               3.3
27              9.7
1               1.4
16              5.2
0               1.2
15              5.0
29             10.6
28             10.4
9               3.8
8               3.3
12              4.1
11              4.1
5               3.0

### House price prediction

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv(r"C:\Users\User\Downloads\housing_price_dataset.csv")
df.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [5]:
def encoding(n):
    if n == 'Rural':
        return 1
    elif n == 'Suburb':
        return 2
    else:
        return 3

In [7]:
df['Neighborhood'] = df['Neighborhood'].apply(encoding)

In [8]:
df.head()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             1       1969  215355.283618
1        2459         3          2             1       1980  195014.221626
2        1860         2          1             2       1970  306891.012076
3        2294         2          1             3       1996  206786.787153
4        2130         5          2             2       2001  272436.239065

In [10]:
X = df[['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood', 'YearBuilt']]
y = df[['Price']]

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y , test_size = 0.2 , random_state = 42)

In [17]:
reg = LinearRegression()
reg.fit(X_train , y_train)
reg.predict([[3200,5,4,3,2010]])

array([[357758.46059454]])

### Evaluation Linear Regression

In [20]:
from sklearn.metrics import mean_squared_error
reg = LinearRegression()
reg.fit(X_train , y_train)
y_pred = reg.predict(X_test)
y_pred
mean_squared_error(y_pred , y_test)

2437053699.886402

In [22]:
from sklearn.metrics import mean_squared_error
reg = LinearRegression()
reg.fit(X_train , y_train)
y_pred = reg.predict(X_test)
y_pred
np.sqrt(mean_squared_error(y_pred , y_test))

49366.52408147045