### HOUSE PRICE PREDICTION USING MACHINE LEARNING
* 1
* Objective :- Maximum profit
* Constraint :- Minimize the time consumption
* Success criteria :- 
    * ML Success Critera :- %
    * Buisness Success Criteria :- 5yrs --> 1yrs
    * Economy Success Critera :- Benifits
* Data understaing :-
    * Dimensions
    * Size
    * Data type
    * Data Shape
    * Data description:- meta data -- DATA ABOUT THE DATA
* 2
* Data Preparation/Preprocessing
    * EDA
        * Distribution
        * Relationship
        * Conclusion
    * Data Cleaning/wrangling
    * Feature Engineering

* **Buisness Objective :- Maximize the profit
* **Constraint :- minimize the time 

In [123]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder , LabelEncoder
from sklearn.linear_model import LinearRegression
from warnings import filterwarnings
filterwarnings('ignore')
import numpy as np

In [91]:
df = pd.read_csv(r"C:\Users\User\Downloads\housing_price_dataset.csv")
df.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [92]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [93]:
df.duplicated().sum()

0

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   SquareFeet    50000 non-null  int64  
 1   Bedrooms      50000 non-null  int64  
 2   Bathrooms     50000 non-null  int64  
 3   Neighborhood  50000 non-null  object 
 4   YearBuilt     50000 non-null  int64  
 5   Price         50000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.3+ MB


#### Splitting data frames into Input (X) and Output(y)

In [95]:
X = df[['SquareFeet' , 'Bedrooms' , 'Bathrooms' , 'Neighborhood' , 'YearBuilt']]
y = df[['Price']]

In [96]:
X.shape , y.shape

((50000, 5), (50000, 1))

In [97]:
y.shape

(50000, 1)

#### Spliiting data into train and test

In [98]:
X_train,X_test,y_train,y_test = train_test_split(X,y , train_size = 0.75 , random_state = 42 )
#Why we use 80% for train --Prediction should be better/accurate with more data
#Why we use 20% less for test
#test_size  both can be used train_size

#### Data Preprocessing
##### OneHotEncoding

In [99]:
pd.get_dummies(df['Neighborhood'] , dtype = int)
#challanges curse of diamensions
# Dummy variable
# COllinear
# because of challenges with OnehotEnc we will go with Labell Enc

Rural  Suburb  Urban
0          1       0      0
1          1       0      0
2          0       1      0
3          0       0      1
4          0       1      0
...      ...     ...    ...
49995      1       0      0
49996      0       1      0
49997      0       1      0
49998      1       0      0
49999      1       0      0

[50000 rows x 3 columns]

In [100]:
pd.get_dummies(df['Neighborhood'] , dtype = int , drop_first = True)

Suburb  Urban
0           0      0
1           0      0
2           1      0
3           0      1
4           1      0
...       ...    ...
49995       0      0
49996       1      0
49997       1      0
49998       0      0
49999       0      0

[50000 rows x 2 columns]

##### Label Encoding

In [101]:
def encoding(n):
    if n == 'Rural':
        return 1
    elif n == 'Suburb':
        return 2
    else:
        return 3

In [102]:
df['Neighborhood'] = df['Neighborhood'].apply(encoding)

In [103]:
df

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0            2126         4          1             1       1969  215355.283618
1            2459         3          2             1       1980  195014.221626
2            1860         2          1             2       1970  306891.012076
3            2294         2          1             3       1996  206786.787153
4            2130         5          2             2       2001  272436.239065
...           ...       ...        ...           ...        ...            ...
49995        1282         5          3             1       1975  100080.865895
49996        2854         2          2             2       1988  374507.656727
49997        2979         5          3             2       1962  384110.555590
49998        2596         5          2             1       1984  380512.685957
49999        1572         5          3             1       2011  221618.583218

[50000 rows x 6 columns]

In [104]:
X = df[['SquareFeet' , 'Bedrooms' , 'Bathrooms' , 'Neighborhood' , 'YearBuilt']]
y = df[['Price']]

In [105]:
X_train,X_test,y_train,y_test = train_test_split(X,y , train_size = 0.75 , random_state = 42 )

In [106]:
X_train

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
27434        2184         2          1             1       1965
13400        2437         3          2             3       1971
883          1166         3          3             2       2003
7303         2033         5          3             1       1952
45124        2431         4          3             2       2007
...           ...       ...        ...           ...        ...
11284        2166         5          3             2       1996
44732        2463         4          1             3       1953
38158        2812         4          2             3       2010
860          2188         3          1             3       1979
15795        2649         5          3             1       1953

[37500 rows x 5 columns]

#### MOdel Building

In [108]:
reg = LinearRegression()

In [109]:
reg.fit(X_train , y_train)

LinearRegression()

In [110]:
reg.predict([[2000,3,2,2,2000]])

C:\Users\User\anaconda3\envs\Python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[221450.98497759]])

In [111]:
reg.predict([[2630,4,4,3,2002]])

C:\Users\User\anaconda3\envs\Python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[296052.87321754]])

In [116]:
reg.intercept_

array([-564.02620204])

In [115]:
reg.coef_

array([[ 9.93324663e+01,  5.33698463e+03,  2.98491641e+03,
         7.15679097e+02, -3.10331410e-02]])

In [118]:
df.corr()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt  \
SquareFeet      1.000000 -0.002638  -0.003275      0.011186   0.000482   
Bedrooms       -0.002638  1.000000   0.007405     -0.004208   0.003147   
Bathrooms      -0.003275  0.007405   1.000000      0.001613   0.003748   
Neighborhood    0.011186 -0.004208   0.001613      1.000000  -0.000174   
YearBuilt       0.000482  0.003147   0.003748     -0.000174   1.000000   
Price           0.750720  0.072624   0.028418      0.016429  -0.002288   

                 Price  
SquareFeet    0.750720  
Bedrooms      0.072624  
Bathrooms     0.028418  
Neighborhood  0.016429  
YearBuilt    -0.002288  
Price         1.000000

#### Model Evaluation`

In [1]:
from sklearn.metrics import mean_squared_error

In [121]:
y_predict = reg.predict(X_test)
y_predict

array([[217895.89313277],
       [135877.88506908],
       [255997.77431057],
       ...,
       [195572.87057016],
       [216356.88288908],
       [125527.67146206]])

In [122]:
mean_squared_error(y_predict , y_test)
#difference between original value and predicted value

2458471332.5340514

In [124]:
np.sqrt(mean_squared_error(y_predict , y_test))

49582.97422033143

#### Linear Regression

In [126]:
from sklearn.metrics import mean_squared_error
reg = LinearRegression()
reg.fit(X_train , y_train)
y_predict = reg.predict(X_test)
y_predict
mean_squared_error(y_predict , y_test)
#difference between original value and predicted value
np.sqrt(mean_squared_error(y_predict , y_test))

49582.97422033143

#### KNN Regression

In [130]:
from sklearn.neighbors import KNeighborsRegressor

In [133]:
knn = KNeighborsRegressor()
knn.fit(X_train , y_train)
y_predict = knn.predict(X_test)
mean_squared_error(y_predict , y_test)
#difference between original value and predicted value
np.sqrt(mean_squared_error(y_predict , y_test))

54397.35057234084

#### Decision tree

In [134]:
from sklearn.tree import DecisionTreeRegressor

In [135]:
dt = DecisionTreeRegressor()
dt.fit(X_train , y_train)
y_predict = dt.predict(X_test)
mean_squared_error(y_predict , y_test)
#difference between original value and predicted value
np.sqrt(mean_squared_error(y_predict , y_test))

73326.04065885424

#### Random Forest

In [136]:
from sklearn.ensemble import RandomForestRegressor

In [137]:
rf = RandomForestRegressor()
rf.fit(X_train , y_train)
y_predict = rf.predict(X_test)
mean_squared_error(y_predict , y_test)
#difference between original value and predicted value
np.sqrt(mean_squared_error(y_predict , y_test))

52902.77118644709