In [1]:
import pandas as pd
import numpy as np
import cv2

In [2]:
df = pd.read_csv(r"C:\Users\User\Downloads\mnist_train.csv\mnist_train.csv")

In [3]:
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [4]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [5]:
X.iloc[0,:]

1x1      0
1x2      0
1x3      0
1x4      0
1x5      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Name: 0, Length: 784, dtype: int64

In [6]:
np.array(X.iloc[0,:])

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [7]:
img = np.array(np.array(X.iloc[0,:],dtype = np.uint8).reshape(28,28))
cv2.imshow("MY IMAGE" , cv2.resize(img , (200,200)))
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [8]:
img = np.array(np.array(X.iloc[2,:],dtype = np.uint8).reshape(28,28))
cv2.imshow("MY IMAGE" , cv2.resize(img , (200,200)))
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [9]:
img = np.array(np.array(X.iloc[500,:],dtype = np.uint8).reshape(28,28))
cv2.imshow("MY IMAGE" , cv2.resize(img , (200,200)))
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [10]:
np.iinfo(np.uint8)

iinfo(min=0, max=255, dtype=uint8)

In [25]:
for i in range(10):  #10 images showing
    img = np.array(np.array(X.iloc[i,:],dtype = np.uint8).reshape(28,28))
    cv2.imshow("MY IMAGE" , cv2.resize(img , (200,200)))
    cv2.waitKey(1000)
    cv2.destroyAllWindows()

#### Images saving in file

In [42]:
for i in range(10):  
    img = np.array(np.array(X.iloc[i,:],dtype = np.uint8).reshape(28,28))
    cv2.imwrite(f'E:\#Data Science Innomatics\Module 6 Ai-ML\Image Data\digits\digit{i}.jpg' , img)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [13]:
X_train,X_test,y_train,y_test = train_test_split(X , y , test_size = 0.2 , random_state = 20 )

In [14]:
log = LogisticRegression()

In [15]:
log.fit(X_train , y_train)

C:\Users\User\anaconda3\envs\Python\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
y_pred = log.predict(X_test)

In [17]:
y_pred

array([9, 5, 7, ..., 8, 1, 8], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test,y_pred)

0.9189166666666667

#### Testing

In [24]:
test_img = cv2.imread(r"E:\#Data Science Innomatics\Module 6 Ai-ML\Image Data\digits\digit3.jpg" , 0)

In [25]:
log.predict([test_img.flatten()])

C:\Users\User\anaconda3\envs\Python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [26]:
test_img = cv2.imread(r"E:\#Data Science Innomatics\Module 6 Ai-ML\Image Data\digits\digit8.jpg" , 0)
log.predict([test_img.flatten()])

C:\Users\User\anaconda3\envs\Python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [27]:
test_img = cv2.imread(r"E:\#Data Science Innomatics\Module 6 Ai-ML\Image Data\digits\digit9.jpg" , 0)
log.predict([test_img.flatten()])

C:\Users\User\anaconda3\envs\Python\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([4], dtype=int64)

### Hand Written Recognition