### Car mileage pridiction
* Objective :- Maximize the Mileage
* Constraint :- Minimize the consumptions
* Data description :-
    1. HP :  Horse Power   (Input Variable)
    2. MPG :  Miles per Gallon  (Output Variable)
    3. VOl : Volume        (Input Variable)
    4. SP :  Speed of the car  (Input Variable)
    5. WT :  weight of the carburetor of car  (Input Variable)
* ML problem type :- Supervised Regression

#### Importing liabraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")

#### Importing Dataset

In [2]:
df = pd.read_csv(r"C:\Users\User\Downloads\Cars.csv")
df.head()

HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

#### Splitting Dataset into INPUT (X) and OUTPUT (y)
#### Splitting INPUT and OUTPUT into Train and test

In [3]:
X = df[['HP' , 'VOL', 'SP', 'WT']]
y = df[['MPG']]
X_train,X_test,y_train,y_test = train_test_split(X,y , train_size = 0.75 , random_state = 42)

In [4]:
X.head()

HP  VOL          SP         WT
0  49   89  104.185353  28.762059
1  55   92  105.461264  30.466833
2  55   92  105.461264  30.193597
3  70   92  113.461264  30.632114
4  53   92  104.461264  29.889149

In [5]:
y.head()

MPG
0  53.700681
1  50.013401
2  50.013401
3  45.696322
4  50.504232

#### ML Model Building 

In [6]:
reg = LinearRegression()
reg.fit(X_train, y_train)
reg.predict([[67,94,109,35]])

array([[42.48506511]])

In [7]:
reg.intercept_

array([19.86673611])

In [8]:
reg.coef_

array([[-0.21342585, -0.46221991,  0.50624127,  0.71960668]])

#### ML Model Evaluation
#### Linear Regression

In [9]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

In [10]:
#Mean Squared Error
reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred
mean_squared_error(y_pred , y_test)

26.464146918755517

In [11]:
#Root Mean Squared Error
reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
y_pred
np.sqrt(mean_squared_error(y_pred , y_test))

5.144331532741209

#### KNN

In [12]:
from sklearn.neighbors import KNeighborsRegressor

In [13]:
#Mean Squared Error
knn = KNeighborsRegressor()
knn.fit(X_train , y_train)
y_pred = knn.predict(X_test)
y_pred
mean_squared_error(y_pred , y_test)

7.698138517989916

In [14]:
#Root Mean Squared Error
knn = KNeighborsRegressor()
knn.fit(X_train , y_train)
y_pred = knn.predict(X_test)
y_pred
np.sqrt(mean_squared_error(y_pred , y_test))

2.7745519490523

#### Decision Tree

In [15]:
from sklearn.tree import DecisionTreeRegressor

In [16]:
#Mean Squared Error
dt = DecisionTreeRegressor()
dt.fit(X_train , y_train)
y_pred = dt.predict(X_test)
y_pred
mean_squared_error(y_pred , y_test)

19.961464045046306

In [17]:
#Root Mean Squared Error
dt = DecisionTreeRegressor()
dt.fit(X_train , y_train)
y_pred = dt.predict(X_test)
y_pred
np.sqrt(mean_squared_error(y_pred , y_test))

4.527889085462427

#### Random Forest

In [18]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
#Mean Squared Error
rf = RandomForestRegressor()
rf.fit(X_train , y_train)
y_pred = rf.predict(X_test)
y_pred
mean_squared_error(y_pred , y_test)

18.268652295919747

In [20]:
#Root Mean Squared Error
rf = RandomForestRegressor()
rf.fit(X_train , y_train)
y_pred = rf.predict(X_test)
y_pred
np.sqrt(mean_squared_error(y_pred , y_test))

4.1300300606482105