 ### Linear Regression

- supervsed ML

- Regression promblem

- **pattern**: The algebric equation / eqaution of Straight Line.
    
- **line** : Which can be represented in 2-dimensional.
    

**Linear Regression**:
    
    - Simple Linear regression: whenever the there is a one single input feature its a simple linear Regression.
        
    - Multiple Linear regression :  whenever the there is a more than one one  input feature its a Multiple Linear Regression.

**Simple Linear Regression(y = mx + c)** 
        
-  equation -> y = mx +c --> m - slope, c-intercept 

- m-> slope w.r.t to x-axis. c-> intercept w.r.t to y-axis

- m - rate of change(dy/dx), change in y if there is a change in x by 1 unit. -> Tangent of angel between line x-axis

- m = y2-y1/x2-x1 , m = Tanx1y1 , m = dy/dx

- c-> intercept w.r.t to y-axis. -> y starting point is c.

- to find the best line for model we use **Residuals**.

- **Residuals** - which measures the distance between the line we considerr to data points.

- then Sum of sqaured the residuals of each line we consider , then the one which have the less values of sum of sqaured of residuals.

**Multiple Linear regression(y = m1x1 + m2x2 + m3x3 + ...mnxn)**

- 3D - **Plane** 

- More than 3D then its a **Hyper Plane**. 

In [1]:
import numpy as np

In [4]:
x = np.array([[4,1] , [7,5] , [6,3] , [8,2]])
x

array([[4, 1],
       [7, 5],
       [6, 3],
       [8, 2]])

In [10]:
y = np.array([[1500],[2300],[6000],[2500]])
y

array([[15000],
       [23000],
       [ 6000],
       [ 2500]])

In [11]:
np.linalg.solve(x,y)

LinAlgError: Last 2 dimensions of the array must be square

**Linear Algebric Equation**

In [14]:
import numpy as np

x = np.array([[4, 1], [7, 5], [6, 3], [8, 2]])
y = np.array([1500, 2300, 6000, 2500])

np.linalg.lstsq(x, y)[0]

C:\Users\User\AppData\Local\Temp\ipykernel_4996\274719052.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(x, y)[0]


array([377.84810127, 215.82278481])

In [16]:
(365*5.5) + (472*2.6)

3234.7

In [23]:
import warnings
warnings.filterwarnings("ignore")

In [24]:
x = np.array([[2.3, 2, 1500], [4.5, 1, 1200], [3.3, 1, 600], [1.6, 2, 750] , [2.8, 1, 450]])
y = np.array([15000 , 26000 , 18000 , 19000 , 21000])
np.linalg.lstsq(x, y)[0]

array([5741.13312115, 6947.14886378,   -7.26747955])

In [25]:
(5741*4.8) + (6947*2) + (-7.26*800)

35642.8