* **Vectors Types**
    * Zero Vector
    * Unit Vector
    * Coinitial Vector
    * Collinear Vector
    * Equal Vector

### Vectors Operation

In [1]:
import numpy as np

In [6]:
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
y = np.matrix([[1,0,1],[2,3,1],[4,2,9]])
y

matrix([[1, 0, 1],
        [2, 3, 1],
        [4, 2, 9]])

In [17]:
z = np.matrix([[12],[14],[12]])
z

matrix([[12],
        [14],
        [12]])

#### Vectors Addition
* **Element wise**
* **Shape must be shape**

In [8]:
x+y

matrix([[ 2,  2,  4],
        [ 6,  8,  7],
        [11, 10, 18]])

#### Vectors Subtraction
* **Element wise**
* **Shape must be shape**

In [9]:
x-y

matrix([[0, 2, 2],
        [2, 2, 5],
        [3, 6, 0]])

#### Vectors Multiplication
* **Element wise**
* **Shape must be shape**

In [14]:
np.multiply(x,y)

matrix([[ 1,  0,  3],
        [ 8, 15,  6],
        [28, 16, 81]])

#### Vectors Multiplication
* **Dot product multiplication**
* **Shape may be differ**

In [18]:
np.dot(x,z)

matrix([[ 76],
        [190],
        [304]])

In [26]:
np.linalg.multi_dot((x,z))

matrix([[ 76],
        [190],
        [304]])

#### Distance between vectors using euclidual distance

In [27]:
x = np.array([1,2,3])
y = np.array([15,2,6])
z = np.array([4,7,6])

In [31]:
dist_xy = np.sqrt(np.sum(np.square(x-y)))
dist_xy

14.317821063276353

In [33]:
dist_yz = np.sqrt(np.sum(np.square(y-z)))
dist_yz

12.083045973594572

In [34]:
dist_xz = np.sqrt(np.sum(np.square(x-z)))
dist_xz

6.557438524302

**Distances**

* **Properties of Distance**
    * If the two data point are same the distance between two point will be zero
    * The distance is always positive
    * Triangle Inequality

* **Types of Distances**
    * Numeric data:- 
        * Eucledean Dist
        * Manhatten Dist
        * Minkowsaki Dist
        * Cosine Similarity dist
    * Catogaric data:-
        * Hamming dist
        * Jaccard Symmatric Dist

### KNN Algorithm
* KNN can be applied for labelled data in supervised ML
* KNN can be used for both Classification & Regression type
* KNN is distance based algorithm
* K represent the number of closed data point{neighbour}

### Distance Metrix

In [2]:
from sklearn.metrics import pairwise_distances
import numpy as np

In [3]:
a = np.array([[1,4,7]])
b = np.array([[4,7,9]])

**Eucledean Distance**

In [7]:
eucli = pairwise_distances(a,b,metric='euclidean')
eucli

array([[4.69041576]])

In [8]:
eucli[0][0]

4.69041575982343

**Manhattan Distance**

In [12]:
manhat = pairwise_distances(a,b,metric='l1')
manhat

array([[8.]])

In [13]:
manhat[0][0]

8.0

In [16]:
manhat = pairwise_distances(a,b,metric='manhattan')
manhat

array([[8.]])

**Cosine Distance**

In [23]:
cosine_dist = pairwise_distances(a,b,metric='cosine')
cosine_dist

array([[0.03222319]])

In [24]:
cosine_sim = 1 - cosine_dist[0][0]
cosine_sim

0.9677768063277397

**Hemming Distance**

In [18]:
hemming = pairwise_distances(a,b,metric='hamming')
hemming

array([[1.]])

**Challenges with distance in KNN**